import type { BuildingDef } from "./types";

export const BUILDINGS: BuildingDef[] = [
  {
    id: "spend",
    href: "/spend",
    label: "Market\nHouse",
    icon: "🛒",
    x: 0,
    z: -47,
    w: 12,
    h: 8,
    d: 10,
    brick: "#2d1b0f",
    roof: "#120b06",
    win: "#fbbf24",
    enter: 14,
    collide: 5.2,
    pillars: true,
    large: true,
  },
  {
    id: "income",
    href: "/income",
    label: "Income\nLedger",
    icon: "📜",
    x: -28,
    z: -8,
    w: 8,
    h: 6,
    d: 7,
    brick: "#2e1a10",
    roof: "#16100a",
    win: "#6ee7b7",
    enter: 11,
    collide: 3.9,
    pillars: false,
    large: false,
  },
  {
    id: "bills",
    href: "/bills",
    label: "Post\nOffice",
    icon: "📬",
    x: -28,
    z: 13,
    w: 8,
    h: 6,
    d: 7,
    brick: "#2a180e",
    roof: "#161008",
    win: "#fdba74",
    enter: 11,
    collide: 3.9,
    pillars: false,
    large: false,
  },
  {
    id: "pay",
    href: "/payments",
    label: "Payment\nHall",
    icon: "🪙",
    x: -28,
    z: 34,
    w: 9,
    h: 7,
    d: 8,
    brick: "#281a0a",
    roof: "#12100a",
    win: "#fcd34d",
    enter: 12,
    collide: 4.3,
    pillars: true,
    large: false,
  },
  {
    id: "debt",
    href: "/debt",
    label: "Debt\nHall",
    icon: "📉",
    x: 0,
    z: 50,
    w: 11,
    h: 8,
    d: 9,
    brick: "#25120e",
    roof: "#110807",
    win: "#fb7185",
    enter: 13,
    collide: 5,
    pillars: true,
    large: true,
  },
  {
    id: "gov",
    href: "/dashboard",
    label: "Governor's\nOffice",
    icon: "🏛",
    x: -28,
    z: -28,
    w: 11,
    h: 9,
    d: 9,
    brick: "#3d2214",
    roof: "#1a1210",
    win: "#ffe066",
    enter: 13,
    collide: 5.1,
    pillars: true,
    large: true,
  },
  {
    id: "trophy",
    href: "/achievements",
    label: "Trophy\nRoom",
    icon: "🏆",
    x: 28,
    z: -28,
    w: 11,
    h: 9,
    d: 9,
    brick: "#2e0f0f",
    roof: "#160808",
    win: "#fca5a5",
    enter: 13,
    collide: 5.1,
    pillars: true,
    large: true,
  },
  {
    id: "obs",
    href: "/forecast",
    label: "Observatory",
    icon: "🔭",
    x: 28,
    z: -8,
    w: 8,
    h: 8,
    d: 8,
    brick: "#0e1a2e",
    roof: "#080e18",
    win: "#bfdbfe",
    enter: 11,
    collide: 4,
    pillars: false,
    large: false,
  },
  {
    id: "cal",
    href: "/calendar",
    label: "Calendar\nHall",
    icon: "🗓️",
    x: 28,
    z: 13,
    w: 8,
    h: 6,
    d: 7,
    brick: "#201808",
    roof: "#100e04",
    win: "#c4b5fd",
    enter: 11,
    collide: 3.9,
    pillars: false,
    large: false,
  },
  {
    id: "set",
    href: "/settings",
    label: "Smithy",
    icon: "⚙️",
    x: 28,
    z: 34,
    w: 8,
    h: 6,
    d: 7,
    brick: "#181818",
    roof: "#0c0c0c",
    win: "#cbd5e1",
    enter: 11,
    collide: 3.9,
    pillars: false,
    large: false,
  },
];
