import type { WorldAsset } from "./types";

export const WORLD_ASSETS: WorldAsset[] = [
  {
    id: "stone-house",
    url: "/models/stone_house_exterior.glb",
    x: -18,
    z: -62,
    scale: 0.55,
    rotY: Math.PI,
    collide: 4.2,
    label: "Stone House",
  },
  {
    id: "tavern",
    url: "/models/tavern_detailed.glb",
    x: 52,
    z: 4,
    scale: 1.8,
    rotY: -Math.PI / 2,
    collide: 7,
    label: "Tavern",
  },
  {
    id: "lighthouse",
    url: "/models/lighthouse.glb",
    x: 62,
    z: -68,
    scale: 2.4,
    rotY: Math.PI,
    collide: 7,
    label: "Lighthouse",
  },
  {
    id: "harbor-ship",
    url: "/models/harbor-ship.glb",
    x: -48,
    z: -70,
    scale: 2,
    rotY: Math.PI / 2,
    collide: 7,
  },
  {
    id: "cannon",
    url: "/models/defense_cannon.glb",
    x: -36,
    z: -50,
    scale: 1,
    rotY: Math.PI / 4,
    collide: 3,
  },
  {
    id: "house-1",
    url: "/models/colonial_house.glb",
    x: 52,
    z: -28,
    scale: 1,
    rotY: Math.PI / 2,
    collide: 5,
  },
  {
    id: "house-2",
    url: "/models/colonial_house.glb",
    x: 54,
    z: -15,
    scale: 1,
    collide: 5,
  },
  {
    id: "house-3",
    url: "/models/colonial_house.glb",
    x: 44,
    z: -40,
    scale: 1,
    rotY: 0.25,
    collide: 5,
  },
  {
    id: "lake",
    url: "/models/lake.glb",
    x: 70,
    y: -0.1,
    z: 55,
    scale: 5,
  },
  {
    id: "glb-tree-west",
    url: "/models/tree.glb",
    x: -42,
    z: -16,
    scale: 1.15,
    collide: 1.4,
  },
  {
    id: "glb-tree-east",
    url: "/models/tree.glb",
    x: 42,
    z: -12,
    scale: 1.05,
    collide: 1.4,
  },
  {
    id: "town-dog",
    url: "/models/town-dog.glb",
    x: 5.5,
    z: 9,
    scale: 0.85,
    rotY: -0.6,
    collide: 1,
  },
  {
    id: "town-cat",
    url: "/models/town-cat.glb",
    x: -5.2,
    z: 11,
    scale: 0.7,
    rotY: 0.8,
  },
  {
    id: "citizen-dock",
    url: "/models/colonial_citizen.glb",
    x: -8,
    z: -24,
    scale: 1,
    rotY: Math.PI * 0.15,
    collide: 0.8,
  },
  {
    id: "lightning",
    url: "/models/lighting_pack_2_forked_lightning.glb",
    x: -42,
    y: 10,
    z: -64,
    scale: 2,
  },
];
