import type { WorldAsset } from "./types";

export const WORLD_ASSETS: WorldAsset[] = [
  {
    id: "stone-house",
    url: "/models/stone_house_exterior.glb",
    x: 0,
    z: -72,
    scale: 2,
    rotY: Math.PI,
    collide: 8,
    label: "Stone House",
  },
  {
    id: "tavern",
    url: "/models/tavern_detailed.glb",
    x: 52,
    z: 4,
    scale: 1.8,
    rotY: -Math.PI / 2,
    collide: 7,
    label: "Tavern",
  },
  {
    id: "lighthouse",
    url: "/models/lighthouse.glb",
    x: 62,
    z: -68,
    scale: 2.4,
    rotY: Math.PI,
    collide: 7,
    label: "Lighthouse",
  },
  {
    id: "harbor-ship",
    url: "/models/harbor-ship.glb",
    x: -48,
    z: -70,
    scale: 2,
    rotY: Math.PI / 2,
    collide: 7,
  },
  {
    id: "cannon",
    url: "/models/defense_cannon.glb",
    x: -36,
    z: -50,
    scale: 1,
    rotY: Math.PI / 4,
    collide: 3,
  },
  {
    id: "house-1",
    url: "/models/colonial_house.glb",
    x: 52,
    z: -28,
    scale: 1,
    rotY: Math.PI / 2,
    collide: 5,
  },
  {
    id: "house-2",
    url: "/models/colonial_house.glb",
    x: 54,
    z: -15,
    scale: 1,
    collide: 5,
  },
  {
    id: "house-3",
    url: "/models/colonial_house.glb",
    x: 44,
    z: -40,
    scale: 1,
    rotY: 0.25,
    collide: 5,
  },
  {
    id: "lake",
    url: "/models/lake.glb",
    x: 70,
    y: -0.1,
    z: 55,
    scale: 5,
  },
  {
    id: "lightning",
    url: "/models/lighting_pack_2_forked_lightning.glb",
    x: -42,
    y: 10,
    z: -64,
    scale: 2,
  },
];
